services:
  backend:
    container_name: back-bridge-container
    image: desafio-bridge-2024-back:1.0
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    container_name: front-bridge-container
    image: desafio-bridge-2024-front:1.0
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
      - VITE_BACK_END_URL=http://localhost:8080/api/primenumber
    ports:
      - "5173:5173"